# Copyright 2018-present Open Networking Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# bbsim values

# CLI switches passed to bbsim

olt_id: 0
nni: 1
pon: 1
onu: 1
auth: false
dhcp: false
delay: 200
c_tag: 900
s_tag: 900

# TODO read this values in the config
olt_tcp_port: 50060
bbsim_api_port: 50070
bbsim_sadis_port: 50074
enablePerf: false
enableEvents: false
kafkaAddress: ":9092"

images:
  bbsim:
    repository: 'voltha/bbsim'
    tag: '{{ .Chart.AppVersion }}'
    pullPolicy: 'Always'

global:
  registry: ''

serviceAccountName: default

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
